-- LogTransaction
CREATE TABLE AuditLog(
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    Action VARCHAR2(50),
    ActionDate DATE
);


CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog(
        TransactionID,
        Action,
        ActionDate
    )
    VALUES(
        :NEW.TransactionID,
        'Transaction Inserted',
        SYSDATE
    );
END;
/